### ISSUE TITLE
10.14.4?

### ISSUE THREAD

**Issue by x-t** [b-ggs/x220-hackintosh#3]
don't seem to boot

**Comment by timbotetsu** [comment]
upgrade your clover to latest version could solve your problem :)

**Comment by x-t** [comment]
updated via clover configurator, boots fine with 10.14.3, with 10.14.4 - it panics during boot :/

**Comment by b-ggs** [comment]
I'll be testing with 10.14.4 this weekend. I'll update you when I've got it working on my X220 :)

**Comment by lutzmor** [comment]
Could be hard to get it working ;), because with 10.14.4 the WindowServer wants to have a metal device and if no device is present the WindowServer wont startup, and apple removed as far as i know all possibilities to use old stuff from HighSierra to "fake" the metal support of the device.

So it seems 10.14.3 is the last mojave version usable on this devices ;).
But if you find something different let me know :).

**Comment by b-ggs** [comment]
Yeah sadly I couldn't get it to boot on 10.14.4 even with updated Clover and all. I've read some people have had some success in upgrading from 10.14.3 to 10.14.4 from SysPrefs so there may be some hope there. I still have a copy of 10.14.3 so I'll try to test that too. I'll keep everyone posted.

**Comment by x-t** [comment]
Okay, I got 10.14.4 (somewhat) working on the X220.
First of all, as I know it, there is no way to upgrade from 10.14.3 to 10.14.4, even with updated patches.
Booting it up was inspired by [this post](https://forum.thinkpads.com/viewtopic.php?p=832239#p832239).
I used the [updated patcher](https://ipfs.io/ipfs/QmT7r7bnuXqkx93voJZJwQeXMVa9zZPTakcWHZp1rsRsVN/macOS%20Mojave%20Patcher.dmg) with a .app of 10.14.4 (downloaded via it).
The installer booted without a battery present in the laptop, and the installed OS booted via the USB as well. Please note I chose to format the drive APFS directly instead of HFS+.
After setting the system up (copying EFI to the drive directly, copying kexts, etc.) it no longer booted and was back to panicking on `IOConsoleUsers: gIOScreenLockState 3`.
My EFI folder can be found in this repo - https://github.com/x-t/x220-mojave-efi
Just throwing stuff out there to narrow down issues.

**Comment by kazunari03** [comment]
I got 10.14.4 and 10.14.5 working on the x220.
In 10.14.4 or later, some blobs are need for start windowserver  when you use non-metal graphics.

In 10.14.4
AppleIntelHD3000Graphics.kext
AppleIntelHD3000GraphicsGA.plugin
AppleIntelHD3000GraphicsGLDriver.bundle
AppleIntelHD3000GraphicsVADriver.bundle
AppleIntelSNBGraphicsFB.kext
AppleIntelSNBVA.bundle
**/System/Library/PrivateFrameworks/GPUSupport.framework
/System/Library/Frameworks/OpenGL.framework**

In 10.14.5 or later,
AppleIntelHD3000Graphics.kext
AppleIntelHD3000GraphicsGA.plugin
AppleIntelHD3000GraphicsGLDriver.bundle
AppleIntelHD3000GraphicsVADriver.bundle
AppleIntelSNBGraphicsFB.kext
AppleIntelSNBVA.bundle
**/System/Library/PrivateFrameworks/GPUSupport.framework
/System/Library/Frameworks/OpenGL.framework
/System/Library/Frameworks/CoreDisplay.framework**

I found easy patching tool 
https://github.com/chris1111/Fix-Graphics-HD-3000-Mojave-10.14-Catalina-10.15

**Comment by x-t** [comment]
I don't know if I got lucky or what, but the 10.14.5 release installed fine, even without the above patcher tool, keeping the old dosdude1 one.

**Comment by x-t** [comment]
![Screenshot](https://cdn.discordapp.com/attachments/581470765661159426/591350979895754752/unknown.png)

After hours of battling with 10.14.4, it seems as 10.14.5 works a LOOOOT better, in fact, I was able to install it twice without any problems. All of the steps stay the same, although for good measure I ran [that](https://github.com/chris1111/Fix-Graphics-HD-3000-Mojave-10.14-Catalina-10.15) installer after the post-install, it didn't seem to change anything, but idk. My EFI configuration that booted is on [the same repo](https://github.com/x-t/x220-mojave-efi). Consider giving a shot, we may have the X220 supported for a long time :D

**Comment by b-ggs** [comment]
Holy crap that's amazing!!! I'm gonna try to bring my X220 into work with me later and test it out. Thank you @x-t and @kazunari03!

**Comment by b-ggs** [comment]
So it's been over a month, but I've found some time to revisit this! I had a pull request (#2) here from back in February with some updated Clover stuff, and to my surprise you were right! It seems to boot up fine now with 10.14.5 and dosdude1's macOS Mojave Patcher version 1.3.3! It's installing on my X220 at the moment, I'll update soon!

**Comment by b-ggs** [comment]
I'd test with 10.14.6, but I don't get good Internet where I live and so I only have an outdated 10.14.5 installer. I do have an installer of it on one of the servers at work, so I'll get on that when I can. I imagine though that if this works out on 10.14.5 we should be golden for .6!

**Comment by b-ggs** [comment]
Damn it works perfectly now

![Screen Shot 2019-08-12 at 3 43 23 AM](https://user-images.githubusercontent.com/6130147/62838802-720af780-bcb3-11e9-8ea1-e931b048ae2f.png)

**Comment by b-ggs** [comment]
Thank you all for your help! I will be updating the guide to check compatibility with 10.14.6 as soon as I can get my hands on an installer.
